#!/bin/bash

# --- Configuration ---
# Path to the python file we need to modify
MANAGER_FILE="apis/openfhe_manager.py"
# Directory where experiment results will be moved
RESULTS_ROOT="outputs/experiment_results"

# Parameters to test
CHUNK_SIZES=(1)
WORKER_COUNTS=(4)
# CHUNK_SIZES=(1 2 4)
# WORKER_COUNTS=(1 2 4 8 16)

# --- Setup ---
# Create a backup of the original python file to restore later
if [ ! -f "${MANAGER_FILE}.bak" ]; then
    echo "Creating backup of $MANAGER_FILE..."
    cp "$MANAGER_FILE" "${MANAGER_FILE}.bak"
fi

mkdir -p "$RESULTS_ROOT"

# --- Main Loop ---
for CHUNK in "${CHUNK_SIZES[@]}"; do
    for WORKER in "${WORKER_COUNTS[@]}"; do
        
        echo "=================================================================="
        echo "Running Experiment: CHUNK_SIZE=$CHUNK | MAX_WORKERS=$WORKER"
        echo "=================================================================="

        # 1. Modify openfhe_manager.py in-place
        # We look for the specific lines defining the variables and replace them.
        # This assumes the format in the file is exactly "    CHUNK_SIZE = <number>"
        sed -i "s/CHUNK_SIZE = [0-9]\+/CHUNK_SIZE = $CHUNK/" "$MANAGER_FILE"
        sed -i "s/MAX_WORKERS = [0-9]\+/MAX_WORKERS = $WORKER/" "$MANAGER_FILE"

        # 2. Execute the existing test script
        # This will run through all cancer types defined in run_tests.sh
        ./run_bio_all_cancers.sh

        # 3. Organize Output
        # Create a specific directory for this configuration
        EXP_DIR="${RESULTS_ROOT}/C${CHUNK}_W${WORKER}"
        mkdir -p "$EXP_DIR"

        # Move the final CSVs generated by run_tests.sh to the experiment folder
        # We check if files exist to avoid errors if a run failed completely
        if ls outputs/*.csv 1> /dev/null 2>&1; then
            echo "Moving results to $EXP_DIR..."
            mv outputs/*.csv "$EXP_DIR/"
            
            # Optional: If you want to keep the JSON summaries too, uncomment below:
            # mv outputs/*.json "$EXP_DIR/"
        else
            echo "WARNING: No CSV results found for this configuration."
        fi

        echo "Experiment C${CHUNK}_W${WORKER} completed."
        echo ""
    done
done

# --- Cleanup ---
# Restore the original file
echo "Restoring original configuration..."
mv "${MANAGER_FILE}.bak" "$MANAGER_FILE"

echo "All experiments completed. Results are in $RESULTS_ROOT/"